const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_APP_MODE: 'CHANGE_APP_MODE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    ADMIN_PROCESS_LOGOUT: 'ADMIN_PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    RESET_USER_INFO: 'RESET_USER_INFO',
    CHANGE_FLA: 'CHANGE_FLA',


    //Cart
    INCREASE_QUANTITY : 'INCREASE_QUANTITY',
    DECREASE_QUANTITY : 'DECREASE_QUANTITY',
    GET_ALL_PRODUCT : 'GET_ALL_PRODUCT',
    GET_NUMBER_CART : 'GET_NUMBER_CART',
    ADD_CART : 'ADD_CART' ,
    UPDATE_CART : 'UPDATE_CART',
    DELETE_CART : 'DELETE_CART',
    DELETE_ITEM: 'DELETE_ITEM'


})

export default actionTypes;