# Github Actions Workflow file that builds and pushes the docker images.
name: pick-bazar-app
env:
  FRONTEND_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/pick-bazar-frontend"
  LARAVEL_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/pick-bazar-laravel"

on:
  push:
    branches:
      - main
    paths:
      - "src/frontend/**"
      - "src/api/**"
      - "!**/README.md"

# Job declaration starts.
jobs:
  react-test:
    runs-on: ubuntu-latest
    # Only run the job if the event is a pull request or push, and there are changes in the src/frontend directory.
    if: contains(github.event.head_commit.modified, 'src/frontend')
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
          cache: 'npm'
      - name: Install Node Dependencies
        run: npm ci
        env:
          CI: TRUE
      - name: Test Code Linting
        run: npm run lint
      - name: Save Code Linting Report JSON
        run: npm run lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"

  laravel-test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'src/api')
    steps:
      - uses: actions/checkout@v2
      - name: "Test Laravel Code"
        uses: Argavyon/laravel-pint-action@7b0629439cc7fbb69ba61aba1ec86090659d3d77 
        id: pint
        with:
          preset: laravel
          verboseMode: true
          testMode: true
          pintVersion: 1.2.1
        continue-on-error: true
      - name: "Lint Results"
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const output = `## Laravel Results
            <details><summary>Show Laravel Results</summary>
            ${steps.pint.outputs.stdout}
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment ({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: "Lint Results"
        uses: actions/github-script@v6
        if: github.event_name == 'push'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const output = `## Laravel Results
            <details><summary>Show Laravel Results</summary>
            ${steps.pint.outputs.stdout}
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.repos.createCommitComment ({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  docker:
    runs-on: ubuntu-latest
    needs: [react-test, laravel-test]
    if: github.event_name == 'push' && (contains(github.event.head_commit.modified, 'src/frontend') || contains(github.event.head_commit.modified, 'src/api'))
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and tag the image with git sha and latest.
      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./src/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_TAG }}:${{ github.sha }}
            ${{ env.FRONTEND_TAG }}:latest
          cache-from: type=registry,ref=${{ env.FRONTEND_TAG }}:latest
          cache-to: type=inline

      - name: Build and push Docker image for laravel
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./src/api/Dockerfile
          push: true
          tags: |
            ${{ env.LARAVEL_TAG }}:${{ github.sha }}
            ${{ env.LARAVEL_TAG }}:latest
          cache-from: type=registry,ref=${{ env.LARAVEL_TAG }}:latest
          cache-to: type=inline

      # Update the image SHA tag in the deployment file.
      - name: Update the image tag in app.tf terraform file
        run: |
          sed -i "s|image = \"${{ env.FRONTEND_TAG }}:.*\"|image = \"${{ env.FRONTEND_TAG }}:${{ github.sha }}\"|g" infra/app.tf
          sed -i "s|image = \"${{ env.LARAVEL_TAG }}:.*\"|image = \"${{ env.LARAVEL_TAG }}:${{ github.sha }}\"|g" infra/app.tf
      
      - name: Commit the changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Pick Bazar Bot"
          author_email: "quanganhdb2510@gmail.com"
          message: "BOT: Update the images' tags in app.tf"
          add: "infra/app.tf"
